import Head from 'next/head'
import SectionOne from '@/components/PageSections/Careers/SectionOne'
import SectionTwo from '@/components/PageSections/Careers/SectionTwo'
import SectionThree from '@/components/PageSections/Careers/SectionThree'
import SectionFour from '@/components/PageSections/Careers/SectionFour'

const Careers = () => {
  return (
    <>
      <Head>
        <title>Careers</title>
        <meta name='description' content='Generated by create next app' />
      </Head>

      <div className='w-full h-full'>
        <SectionOne />
        <SectionTwo />
        <SectionThree />
        <SectionFour />
      </div>
    </>
  )
}

export default Careers
