import Head from 'next/head'

import SectionOne from '@/components/PageSections/SellYourHome/SectionOne'
import SectionTwo from '@/components/PageSections/SellYourHome/SectionTwo'
import SectionThree from '@/components/PageSections/SellYourHome/SectionThree'
import SectionFour from '@/components/PageSections/SellYourHome/SectionFour'

const SellYourHome = () => {
  return (
    <>
      <Head>
        <title>Sell Your Home</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <SectionOne />
      <SectionTwo />
      <SectionThree />
      <SectionFour />
    </>
  )
}

export default SellYourHome
