import Head from 'next/head'
import BasicContainer from '@/components/Hardware/Containers/BasicContainer'
import SectionOne from '@/components/PageSections/BuyYourHome/Application/SectionOne'
import SectionTwo from '@/components/PageSections/BuyYourHome/Application/SectionTwo'
import SectionThree from '@/components/PageSections/BuyYourHome/Application/SectionThree'
import SectionFour from '@/components/PageSections/BuyYourHome/Application/SectionFour'
import SectionFive from '@/components/PageSections/BuyYourHome/Application/SectionFive'
import { useState } from 'react'

const Application = () => {
  let [sectionOneConfirmOn, setSectionOneConfirmOn] = useState(false)
  let [sectionTwoConfirmOn, setSectionTwoConfirmOn] = useState(false)
  let [sectionThreeConfirmOn, setSectionThreeConfirmOn] = useState(false)
  let [sectionFourConfirmOn, setSectionFourConfirmOn] = useState(false)
  const [address, setAddress] = useState('')
  const [propertyId, setPropertyId] = useState('')
  const [contactId, setContactId] = useState('')
  const [contactType, setContactType] = useState('')
  const [user, setUser] = useState('')
 
  return (
    <>
      <Head>
        <title>Buy Your Home Application</title>
        <meta name='description' content='Generated by create next app' />
      </Head>

      <section className='w-full h-full bg-vb_white-500 pt-8 pb-32'>
        <BasicContainer>
          <div className='w-full flex flex-col justify-center items-center min-h-[50vh] bg-white mx-auto rounded-xl shadow-lg shadow-vb_gray-200'>
            <h1 className='text-vb_teal-600 text-2xl lg:text-5xl mx-2 text-center font-black uppercase mt-10'>
              Resident Purchase Program Inquiry Form
            </h1>
            { sectionOneConfirmOn === false ? (
              <SectionOne 
                setSectionOneConfirmOn={setSectionOneConfirmOn} 
                setAddress={setAddress} 
                address={address} 
                setPropertyId={setPropertyId} 
                propertyId={propertyId} 
              />
            )  : sectionOneConfirmOn === true && sectionTwoConfirmOn === false ? (
              <SectionTwo
                propertyId={propertyId}
                setPropertyId={setPropertyId} 
                contactId={contactId}
                setContactId={setContactId}
                contactType={contactType}
                setContactType={setContactType}
                setSectionOneConfirmOn={setSectionOneConfirmOn} 
                setSectionTwoConfirmOn={setSectionTwoConfirmOn} 
              />              
            ) : sectionTwoConfirmOn === true && sectionThreeConfirmOn === false ? (
              <SectionThree 
                propertyId={propertyId}
                contactId={contactId}
                contactType={contactType}
                setUser={setUser}
                setSectionTwoConfirmOn={setSectionTwoConfirmOn} 
                setSectionThreeConfirmOn={setSectionThreeConfirmOn} 
              />            
            ) : sectionThreeConfirmOn === true && sectionFourConfirmOn === false ? (
              <SectionFour               
                contactId={contactId}
                propertyId={propertyId}
                user={user}
                setSectionThreeConfirmOn={setSectionThreeConfirmOn}  
                setSectionFourConfirmOn={setSectionFourConfirmOn} />             
            ) : sectionFourConfirmOn === true ? (
              <SectionFive user={user} />
            ) : null }
          </div>
        </BasicContainer>
      </section>
    </>
  )
}

export default Application
