import Head from 'next/head'
import SectionOne from '@/components/PageSections/BuyYourHome/SectionOne'
import SectionTwo from '@/components/PageSections/BuyYourHome/SectionTwo'

const BuyYourHome = () => {
  return (
    <>
      <Head>
        <title>Buy Your Home</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <div className='w-full'>
        <SectionOne />
        <SectionTwo />
      </div>
    </>
  )
}

export default BuyYourHome
