import Head from 'next/head'
import BasicContainer from '@/components/Hardware/Containers/BasicContainer'
import Image from 'next/image'
import Link from 'next/link'
import fbIcon from '../../public/img/pages/QuickLinks/Icon-FB-QuickLinks.png'
import inIcon from '../../public/img/pages/QuickLinks/Icon-IN-QuickLinks.png'
import twIcon from '../../public/img/pages/QuickLinks/Icon-TW-QuickLinks.png'
import ytIcon from '../../public/img/pages/QuickLinks/Icon-YT-QuickLinks.png'

const QuickLinks = () => {
  return (
    <>
      <Head>
        <title>QuickLinks</title>
        <meta name='description' content='Generated by create next app' />
      </Head>

      <div className={`bg-white sm:bg-vb_blue-900 bg-no-repeat bg-cover bg-center w-full h-[100vh]`}>
        <BasicContainer>
          <div className='4xl:flex 4xl:flex-row 4xl:justify-center 4xl:items-center 4xl:w-[454px] 4xl:h-[800px] 4xl:bg-vb_green-200 4xl:mx-auto 4xl:mt-[2%] 4xl:rounded-2xl'>
            <div className='w-[320px] sm:w-[400px] bg-white text-center mx-auto mt-4 sm:mt-20 4xl:mt-0 py-12 rounded-lg'>
              <div>
                <h2 className='text-vb_blue-800 text-5xl font-black'>RESOURCES</h2>
                <ul className='my-12 px-6 text-white font-[600] tracking-widest'>
                  <li className='bg-vb_green-500 hover:bg-vb_green-400 my-3 rounded-md shadow-md shadow-vb_gray-200 hover:shadow-lg hover:shadow-vb_gray-300 cursor-pointer transition-all duration-300 ease-in-out'>
                    <Link
                      className='w-full h-full block py-2'
                      href={
                        'https://vinebrook-reslisting.securecafe.com/residentservices/apartmentsforrent/userlogin.aspx'
                      }
                      target='_blank'
                    >
                      MAKE A PAYMENT
                    </Link>
                  </li>
                  <li className='bg-vb_green-500 hover:bg-vb_green-400 my-3 rounded-md shadow-md shadow-vb_gray-200 hover:shadow-lg hover:shadow-vb_gray-300 cursor-pointer transition-all duration-300 ease-in-out'>
                    <Link
                      className='w-full h-full block py-2'
                      href={'https://www.exclusive.com/service-request'}
                      target='_blank'
                    >
                      SERVICE REQUEST
                    </Link>
                  </li>
                  <li className='bg-vb_green-500 hover:bg-vb_green-400 my-3 rounded-md shadow-md shadow-vb_gray-200 hover:shadow-lg hover:shadow-vb_gray-300 cursor-pointer transition-all duration-300 ease-in-out'>
                    <Link className='w-full h-full block py-2' href={'/resident/hardship'} target='_blank'>
                      HARDSHIP RELIEF PROGRAM
                    </Link>
                  </li>
                  <li className='bg-vb_green-500 hover:bg-vb_green-400 my-3 rounded-md shadow-md shadow-vb_gray-200 hover:shadow-lg hover:shadow-vb_gray-300 cursor-pointer transition-all duration-300 ease-in-out'>
                    <Link className='w-full h-full block py-2' href={'/operation-hope'} target='_blank'>
                      FINANCIAL COACHING
                    </Link>
                  </li>
                  <li className='bg-vb_green-500 hover:bg-vb_green-400 my-3 rounded-md shadow-md shadow-vb_gray-200 hover:shadow-lg hover:shadow-vb_gray-300 cursor-pointer transition-all duration-300 ease-in-out'>
                    <Link className='w-full h-full block py-2' href={'/resident/faq'} target='_blank'>
                      FAQ
                    </Link>
                  </li>
                  <li className='bg-vb_green-500 hover:bg-vb_green-400 my-3 rounded-md shadow-md shadow-vb_gray-200 hover:shadow-lg hover:shadow-vb_gray-300 cursor-pointer transition-all duration-300 ease-in-out'>
                    <Link className='w-full h-full block py-2' href={'/contacts'} target='_blank'>
                      CUSTOMER SERVICE
                    </Link>
                  </li>
                </ul>
              </div>
              <div className='4xl:mt-24'>
                <h2 className='text-vb_blue-800 text-5xl font-black'>FOLLOW US!</h2>
                <ul className='flex flex-row justify-between mt-8 4xl:mt-16 px-6'>
                  <li>
                    <Link href={'https://www.facebook.com/exclusive'} target='_blank'>
                      <Image
                        src={fbIcon}
                        alt={'fbIcon'}
                        className='w-12 shadow-sm shadow-vb_gray-200 hover:shadow-md hover:shadow-vb_gray-300 rounded-full transition-all duration-300 ease-in-out'
                        width={0}
                        height={0}
                        sizes='100'
                      />
                    </Link>
                  </li>
                  <li>
                    <Link href={'https://www.instagram.com/exclusive/'} target='_blank'>
                      <Image
                        src={inIcon}
                        alt={'inIcon'}
                        className='w-12 shadow-sm shadow-vb_gray-200 hover:shadow-md hover:shadow-vb_gray-300 rounded-full transition-all duration-300 ease-in-out'
                        width={0}
                        height={0}
                        sizes='100'
                      />
                    </Link>
                  </li>
                  <li>
                    <Link
                      href={'https://twitter.com/i/flow/login?redirect_after_login=%2Fexclusive'}
                      target='_blank'
                    >
                      <Image
                        src={twIcon}
                        alt={'twIcon'}
                        className='w-12 shadow-sm shadow-vb_gray-200 hover:shadow-md hover:shadow-vb_gray-300 rounded-full transition-all duration-300 ease-in-out'
                        width={0}
                        height={0}
                        sizes='100'
                      />
                    </Link>
                  </li>
                  <li>
                    <Link href={'https://www.youtube.com/@exclusive/videos'} target='_blank'>
                      <Image
                        src={ytIcon}
                        alt={'ytIcon'}
                        className='w-12 shadow-sm shadow-vb_gray-200 hover:shadow-md hover:shadow-vb_gray-300 rounded-full transition-all duration-300 ease-in-out'
                        width={0}
                        height={0}
                        sizes='100'
                      />
                    </Link>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </BasicContainer>
      </div>
    </>
  )
}

export default QuickLinks
