import Head from 'next/head'
import SectionOne from '@/components/PageSections/Cincinnati/Impact/SectionOne'
import SectionTwo from '@/components/PageSections/Cincinnati/Impact/SectionTwo'
import SectionThree from '@/components/PageSections/Cincinnati/Impact/SectionThree'
import SectionFour from '@/components/PageSections/Cincinnati/Impact/SectionFour'

const CincinnatiImpact = () => {
  return (
    <>
      <Head>
        <title>Cincinnati Impact</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <div>
        <SectionOne />
        <SectionTwo />
        <SectionThree />
        <SectionFour />
      </div>
    </>
  )
}

export default CincinnatiImpact
