/* eslint-disable react/no-unescaped-entities */
import Head from 'next/head'
import BasicContainer from '@/components/Hardware/Containers/BasicContainer'

const TermsPrivacy = () => {
  return (
    <>
      <Head>
        <title>Terms & Privacy</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <section className='bg-vb_green-200 w-full py-10 mb-10'>
        <BasicContainer>
          <h1 className='text-5xl text-white font-extrabold tracking-wide'>Terms and Privacy</h1>
        </BasicContainer>
      </section>
      <section className=''>
        <BasicContainer>
          <h2 className='text-3xl font-normal tracking-wide mb-5'>Welcome Future Resident!</h2>
          <p className='text-xl text-left leading-7'>
            Exclusive Off Market DealsProperty Management Company, LLC ("Exclusive Off Market Deals") is pleased to
            welcome you to{' '}
            <a href='https://www.vinebrookhomes.com' target='_blank'>
              www.vinebrookhomes.com
            </a>{' '}
            (the "Site"). You must accept and agree to be bound by the following Terms of Service. The Terms of Service
            are a legal contract between you and Exclusive Off Market Dealsrelated to identification of a home for you,
            which includes computer software and, as applicable, associated media, printed materials, and "online" or
            electronic documentation and information (collectively, the "Service"). YOU ARE ONLY ALLOWED TO USE THE
            SERVICE IF YOU CAN ENTER INTO A BINDING CONTRACT WITH Exclusive Off Market Deals. BY REGISTERING TO USE THE
            SERVICE, OR BY INSTALLING, COPYING, OR OTHERWISE USING THE SERVICE, YOU AGREE TO BE BOUND BY THESE TERMS AND
            CONDITIONS, INCLUDING THE WARRANTY DISCLAIMERS, LIMITATIONS OF LIABILITY AND TERMINATION PROVISIONS BELOW.
            IF YOU DO NOT AGREE TO SUCH TERMS AND CONDITIONS, DO NOT INSTALL OR USE THIS APPLICATION OR THE SERVICE AND
            EXIT NOW.
          </p>

          <h2 className='text-3xl font-normal tracking-wide mb-5 mt-5'>Access and Use of the Site</h2>
          <p className='text-xl text-left leading-7'>
            Access to and use of this website (the "Site") and its contents are permitted only for finding a home for
            rent, and available resident services. Any other access to or use of this Site or its contents is
            unauthorized. We reserve the right to deactivate or suspend use of the Service by anyone for any reason or
            no reason at all. Information and materials posted by Exclusive Off Market Dealsare provided for general
            reference only and are not warranted to be free of errors, omissions or potential interruptions.
          </p>

          <h2 className='text-3xl font-normal tracking-wide mb-5 mt-5'>Services Powered by Third Parties</h2>
          <p className='text-xl text-left leading-7'>
            Certain services offered on our Site are actually offered by parties other than Exclusive Off Market Deals.
            In these situations the relevant third party will have access to data collected as part of the services
            rendered, and you are asked to review the Terms of Service and the privacy policy of the relevant third
            party before using the services. It is expected that such third party service providers may share the
            information they collected with us.
          </p>

          <h2 className='text-3xl font-normal tracking-wide mb-5 mt-5'>NO WARRANTIES, LIMITATION OF LIABILITY</h2>
          <p className='text-xl text-left leading-7'>
            THE SERVICES AND THIS SITE ARE PROVIDED “AS IS, WHERE IS” AS AN ACCOMODATION WITHOUT WARRANTY OF ANY KIND.
            ALL USE IS AT YOUR SOLE RISK. Exclusive Off Market DealsSPECIFICALLY DISCLAIMS ALL WARRANTIES, EXPRESS OR
            IMPLIED, INCLUDING, WITHOUT LIMITATION, ANY WARRANTY OF TITLE, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR
            PURPOSE. IN NO EVENT SHALL Exclusive Off Market Deals, ITS OFFICERS, DIRECTORS, EMPLOYEES, AGENTS,
            AFFILIATES, ADVERTISERS, OR DATA PROVIDERS BE LIABLE FOR ANY INDIRECT, SPECIAL, INCIDENTAL, CONSEQUENTIAL OR
            PUNITIVE DAMAGES (INCLUDING BUT NOT LIMITED TO LOSS OF DATA, LOSS OF USE, OR LOSS OF PROFITS) WHETHER IN AN
            ACTION IN CONTRACT, TORT (INCLUDING BUT NOT LIMITED TO NEGLIGENCE), EQUITY OR OTHERWISE, ARISING OUT OF OR
            IN ANY WAY CONNECTED WITH THE USE OF THIS SITE OR THE SERVICE. YOUR SOLE REMEDY IN THE EVENT OF ANY
            DEFICIENCY OR ERROR SHALL BE TO REQUEST THAT Exclusive Off Market DealsCORRECT THE MATTER OR, IF Exclusive
            Off Market DealsFAILS TO DO SO, FOR YOU TO DISCONTINUE USE OF THE SERVICE.
          </p>

          <h2 className='text-3xl font-normal tracking-wide mb-5 mt-5'>INDEMINIFICATION</h2>
          <p className='text-xl text-left leading-7'>
            You agree to defend, indemnify, and hold Exclusive Off Market Dealsharmless from and against any claims,
            damages, costs, liabilities, and expenses (including, but not limited to, reasonable attorneys' fees)
            arising out of or related to your use of the Site and the Service, including, without limitation, any actual
            or threatened suit, demand, or claim made against Exclusive Off Market Dealsarising out of or relating to
            the Services, your conduct, your violation of these Terms of Service, or your violation of the rights of any
            third party.
          </p>

          <h2 className='text-3xl font-normal tracking-wide mb-5 mt-5'>Limitation of Claims</h2>
          <p className='text-xl text-left leading-7'>
            Regardless of any statute or law to the contrary, any claim or cause of action arising out of or related to
            your use of the Services must be filed within one (1) year after such claim or cause of action arose, or
            else that claim or cause of action will be barred forever. You agree to accept sole responsibility for any
            use of internet facilities conducted or permitted by you or your Clients; the conduct of any business,
            advertising, marketing or sales in connection therewith; and any negligent or illegal act or omission of you
            or your agents, contractors, servants, employees, or other users or accesses.
          </p>

          <h2 className='text-3xl font-normal tracking-wide mb-5 mt-5'>Fair Housing/Equal Housing Opportunity</h2>
          <p className='text-xl text-left leading-7'>
            Exclusive Off Market Dealsis an Equal Housing Opportunity company, which means Exclusive Off Market Deals(as
            well as all of our affiliated entities and employees) complies with the Fair Housing Act and other
            applicable federal, state and local anti-housing discrimination laws. The federal Fair Housing Act prohibits
            discrimination in housing because of race, color, national origin, religion, sex, disability and the
            presence of children. Exclusive Off Market Deals also operates in states and local jurisdictions, which have
            additional fair housing laws and added protected classes. Exclusive Off Market Dealsis also responsible for
            complying with those laws and regulations. As such, all rental properties identified in this Site are
            subject to the federal Fair Housing Act and its state law counterparts. Exclusive Off Market Dealswill not
            knowingly permit or allow any discriminatory conduct in the rental of its properties that violates
            applicable law. Complaints concerning discriminatory practices in housing may be filed with the local office
            of the U.S. Department of Housing and Urban Development ("HUD").
          </p>

          <h2 className='text-3xl font-normal tracking-wide mb-5 mt-5'>Arbitration</h2>
          <p className='text-xl text-left leading-7'>
            Any claim or dispute arising out of or relating to these Terms of Service or the Service will be settled by
            binding arbitration before a single arbitrator in accordance with the commercial arbitration rules of the
            American Arbitration Association ("AAA"). Any such controversy or claim must be arbitrated on an individual
            basis, and must not be consolidated in any arbitration with any claim or controversy of any other party.
          </p>

          <h2 className='text-3xl font-normal tracking-wide mb-5 mt-5'>
            Modification of our Services, and These Terms
          </h2>
          <p className='text-xl text-left leading-7'>
            We may also change or modify these Terms of Service, or any policy or guideline of this Site, at any time
            and in our sole discretion. You waive any right you may have to receive specific notice of such changes or
            modifications. Your continued use of the Site or Services following the posting of changes or modifications
            will confirm your acceptance of such changes or modifications. These Terms became effective on April 1,
            2016.
          </p>

          <h2 className='text-3xl font-normal tracking-wide mb-5 mt-5'>Privacy Policy</h2>
          <p className='text-xl text-left leading-7'>
            This Privacy Policy governs the manner in which Exclusive Off Market Dealscollects, uses, maintains, and
            discloses information collected from users (each, a "User") of the www.vinebrookhomes.com website ("Site").
            This privacy policy applies to the Site and all products and services offered by Exclusive Off Market Deals.
          </p>

          <h2 className='text-3xl font-normal tracking-wide mb-5 mt-5'>Personal identification information</h2>
          <p className='text-xl text-left leading-7'>
            We may collect personal identification information from Users in a variety of ways, including, but not
            limited to, when Users visit our site, fill out a form, and in connection with other activities, services,
            features, or resources we make available on our Site. As appropriate, we may ask Users for their names,
            email addresses, mailing addresses, phone numbers, and credit card information. However, Users may visit our
            Site anonymously. We will collect personal identification information from Users only if they voluntarily
            submit such information to us. Users can always refuse to supply personally identification information,
            except that it may prevent them from engaging in certain Site-related activities.
          </p>

          <h2 className='text-3xl font-normal tracking-wide mb-5 mt-5'>Non-personal identification information</h2>
          <p className='text-xl text-left leading-7'>
            We may collect non-personal identification information about Users whenever they interact with our Site.
            Non-personal identification information may include the browser name, the type of computer, and technical
            information about Users’ means of connection to our Site, such as the operating system and the Internet
            service providers utilized and other similar information.
          </p>

          <h2 className='text-3xl font-normal tracking-wide mb-5 mt-5'>Web browser cookies</h2>
          <p className='text-xl text-left leading-7'>
            Our Site may use "cookies" to enhance Users’ experiences. Web browsers place these cookies on Users’ hard
            drives for record-keeping purposes and tracking information. Users may choose to set their web browsers to
            refuse cookies or alert them when cookies are being sent. If they do so, some parts of the Site may not
            function properly. Compliance with children's online privacy protection act Protecting the privacy of the
            very young is especially important. For that reason, we never collect or maintain information at our Site
            from those we actually know are minors, and no part of our website is structured to attract anyone under 13.
          </p>

          <h2 className='text-3xl font-normal tracking-wide mb-5 mt-5'>Changes to this privacy policy</h2>
          <p className='text-xl text-left leading-7'>
            You acknowledge and agree that it is your responsibility to review this privacy policy periodically and
            become aware of modifications.
          </p>

          <h2 className='text-3xl font-normal tracking-wide mb-5 mt-5'>Your acceptance of these terms</h2>
          <p className='text-xl text-left leading-7'>
            By using this Site, you signify your acceptance of this policy. If you do not agree to this policy, please
            do not use our Site. Your continued use of the Site following the posting of changes to this policy will be
            deemed your acceptance of those changes. This document was last updated on April 1, 2016.
          </p>
        </BasicContainer>
      </section>
      <section className='bg-vb_green-200 w-full py-10 mb-10 mt-5'>
        <BasicContainer>
          <h1 className='text-4xl text-white font-extrabold tracking-wide'>SMS/MMS Terms and Conditions</h1>
        </BasicContainer>
      </section>

      <section className=''>
        <BasicContainer>
          <h2 className='text-3xl font-normal tracking-wide mb-5'>Program Description</h2>
          <p className='text-xl text-left leading-7 mb-5'>
            Exclusive Off Market Dealsuses SMS/MMS text messaging to correspond with our residents and prospects to
            communicate property management activities. Activities may include but is not limited to responding to an
            application, addressing a service request, renewing your lease, and paying your rent.
          </p>

          <h2 className='text-3xl font-normal tracking-wide mb-5'>Message Frequency</h2>
          <p className='text-xl text-left leading-7 mb-5'>
            The number of text messages you will receive will vary. You will receive a maximum of 20 text messages over
            a one month period.
          </p>

          <h2 className='text-3xl font-normal tracking-wide mb-5'>Cost</h2>
          <p className='text-xl text-left leading-7 mb-5'>
            Message and data rates may apply to each text message sent or received from Exclusive Off Market Dealstext
            messages, dependent upon your mobile telephone service rate plan. Please contact your mobile carrier
            provider for your specific plan and pricing. Exclusive Off Market Dealsdoes not charge a separate fee for
            sending our text messages.
          </p>

          <h2 className='text-3xl font-normal tracking-wide mb-5'>Supported Carriers</h2>
          <p className='text-xl text-left leading-7 mb-5'>
            Supported carriers may change from time to time, but currently include AT&T, Metro PCS, Sprint, T-Mobile,
            and Verizon Wireless.
          </p>
          <p className='text-xl text-left leading-7 mb-5'>
            T-Mobile&copy; is not liable for delayed or undelivered messages.
          </p>

          <h2 className='text-3xl font-normal tracking-wide mb-5'>How to Opt-In</h2>
          <p className='text-xl text-left leading-7 mb-5'>
            To opt-in to receive Exclusive Off Market Dealstext messages, please text <b>JOIN</b>​ to 91804
          </p>

          <h2 className='text-3xl font-normal tracking-wide mb-5'>How to Opt-Out</h2>
          <p className='text-xl text-left leading-7 mb-5'>
            To stop receiving Exclusive Off Market Dealstext messages, please text <b>STOP</b>​ to 91804.
          </p>

          <h2 className='text-3xl font-normal tracking-wide mb-5'>Privacy</h2>
          <p className='text-xl text-left leading-7 mb-5'>
            Users mobile information will not be shared. Please see above to view Exclusive Off Market DealsTerms &amp;
            Privacy information.
          </p>

          <h2 className='text-3xl font-normal tracking-wide mb-5'>
            Access or Delivery to Mobile Network is Not Guaranteed
          </h2>
          <p className='text-xl text-left leading-7 mb-5'>
            Delivery of information and content may fail to deliver to your mobile device for a variety of reasons. You
            understand and acknowledge that mobile network services are outside of Exclusive Off Market Dealscontrol and
            Exclusive Off Market Deals is not responsible or liable for any issues arising from network failures.
          </p>

          <h2 className='text-3xl font-normal tracking-wide mb-5'>Support/Help</h2>
          <p className='text-xl text-left leading-7 mb-5'>
            If you need assistance with Exclusive Off Market Dealstext messages, please text HELP​ to 91804. If you have
            questions regarding these SMS/MMS Terms and Conditions or Exclusive Off Market Dealstext messaging service,
            please call us at{' '}
            <a
              href='tel:+18555135678'
              className='text-vb_green-500 hover:text-vb_green-400 underline transition-all duration-150 ease-in-out'
            >
              +1(855)513-5678
            </a>{' '}
            or Email{' '}
            <a
              href='mailto:customerservice@vinebrookhomes.com'
              className='text-vb_green-500 hover:text-vb_green-400 break-all sm:break-normal underline transition-all duration-150 ease-in-out'
            >
              customerservice@vinebrookhomes.com
            </a>
          </p>

          <p className='text-xl text-left leading-7 mb-5'>SMS/MMS Portion was last updated on August 1,2022.</p>
        </BasicContainer>
      </section>
    </>
  )
}

export default TermsPrivacy
