import Head from 'next/head'
import TopCarousel from '@/components/PageSections/AboutUs/TopCarousel'
import MainText from '@/components/PageSections/AboutUs/MainText'
import Sidebar from '@/components/PageSections/AboutUs/Sidebar'

const AboutUs = () => {
  return (
    <>
      <Head>
        <title>About Us</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <TopCarousel />
      <div className='flex flex-col lg:flex-row w-full h-auto lg:h-[1450px] xl:h-[1170px] 2xl:h-[1100px] 3xl:h-[1000px] 4xl:h-[920px]'>
        <MainText />
        <Sidebar />
      </div>
    </>
  )
}

export default AboutUs
