import Head from 'next/head'
import NewsBanner from '@/components/PageSections/NewsRoom/MainPage/NewsBanner'
import Highlights from '@/components/PageSections/NewsRoom/MainPage/Highlights'
import LatestNews from '@/components/PageSections/NewsRoom/MainPage/LatestNews/LatestNews'
import PressKits from '@/components/PageSections/NewsRoom/MainPage/PressKits/PressKits'
import AboutVB from '@/components/PageSections/NewsRoom/MainPage/AboutVB'

const NewsRoom = () => {
  return (
    <>
      <Head>
        <title>NewsRoom</title>
        <meta name='description' content='Generated by create next app' />
      </Head>

      <div>
        <NewsBanner />
        <div className='w-full flex flex-col-reverse lg:flex-row'>
          <div className='w-full lg:w-2/3 flex flex-col'>
            <Highlights />
            <LatestNews />
            <PressKits />
          </div>
          <div className='sticky lg:relative top-20 lg:top-0 w-full lg:w-1/3'>
            <AboutVB />
          </div>
        </div>
      </div>
    </>
  )
}

export default NewsRoom
