import Head from 'next/head'
import Image from 'next/image'
import classNames from 'classnames'
import React, { useEffect, useState, useCallback } from 'react'
import { MarkerF, MarkerClustererF } from '@react-google-maps/api'
import { v4 as uuidv4 } from 'uuid'

const BathsBathrooms = () => {
  return (
    <>
      <Head>
        <title>BathsBathrooms</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <div className='w-full flex flex-wrap justify-center text-white bg-sky-700 border-b-2	p-5'>
        <div className='text-6xl font-extrabold	'>
          <h1>FIND YOUR NEXT HOME</h1>
        </div>
      </div>
      <div className='w-full'>Hello World!</div>
    </>
  )
}

export default BathsBathrooms
