import Head from 'next/head'
import Image from 'next/image'
import Dropdown from './components/Dropdown'
import ProspectiveResidentModal from './components/Modal'
import ContactBanner from '@/public/img/pages/contacts/contact-banner.jpg'
import BasicContainer from '@/components/Hardware/Containers/BasicContainer'

const Contacts = () => {
  return (
    <>
      <Head>
        <title>Contact Us</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <section>
        <Image
          src={ContactBanner}
          width={0}
          height={0}
          sizes={100}
          alt={'Contact Banner'}
          priority={true}
          className='w-full'
        />
      </section>
      <section>
        <BasicContainer>
          <div>
            <p className='text-2xl mt-10'>
              <b className='font-semibold'>Existing Residents</b> - to submit service requests and to pay your account
              balance online please {''}
              <a
                href='https://vinebrook-reslisting.securecafe.com/residentservices/apartmentsforrent/userlogin.aspx'
                className='underline text-blue-600 hover:text-blue-800'
                target='_blank'
              >
                Visit our Resident Services Portal
              </a>
            </p>
            <div className='text-2xl mt-10'>
              <p className='inline'>
                <b className='font-semibold'>Prospective Residents</b> - we want to help you find your perfect rental
                home. Get the process started by filling out our {''}
              </p>
              <span className='inline'>
                <ProspectiveResidentModal />
              </span>
              <p className='inline'>
                {''} and one of our Leasing Team Members will be in contact within the next 24 Hours.
              </p>
            </div>
          </div>
        </BasicContainer>
      </section>
      <section className='w-full my-10'>
        <BasicContainer>
          <h2 className='text-3xl md:text-[40px] text-center font-black leading-10 mt-20'>
            GET IN TOUCH WITH YOUR LOCAL OFFICE
          </h2>
          <Dropdown />
        </BasicContainer>
      </section>
    </>
  )
}

export default Contacts
